// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Proyecto IDMA — wipeaufqdiohfdtcbhac. Las VITE_* pueden sobreescribir vía .env en build.
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL || 'https://wipeaufqdiohfdtcbhac.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  'sb_publishable_2reG5ddK8AVmbqyu5RtKsQ_DMI5h6LK';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
